### ISSUE TITLE
Please impl common traits such  as `Debug`

### ISSUE THREAD

**Issue by Forsworns** [Pscheidl/enum-collections#11]
Though we can build a new wrapper for EnumTable/EnumMap when using it, it's better if you could impl it in this crate :)

Or simply provide an interface `Into<HashMap>`, it would be helpful for debug/serialization.

**Comment by Pscheidl** [comment]
@Forsworns `Debug` has been implemented and released in version `0.8.0`. https://crates.io/crates/enum-collections

`Eq` and `PartialEq` to be done separately.

**Comment by Pscheidl** [comment]
@Forsworns FYI `Eq` and `PartialEq` were done as a part of #13 and released in version `0.9.0`.
