### ISSUE TITLE
EnumMap indexing doesn't match standart library

### ISSUE THREAD

**Issue by SpecificProtagonist** [Pscheidl/enum-collections#3]
In the standard library, indexing panics when the index isn't found. Indexing `EntityMap` returns a reference to an option instead.

**Comment by Pscheidl** [comment]
This is because EnumMap initializes everything to None. That is the only difference it has right now compared to EnumTable. It forces usage of `Option`. Otherwise the functionality is completely the same and could be replaced by an EnumTable. With the recent API changes, it actually could be done.
