### ISSUE TITLE
Store data inline

### ISSUE THREAD

**Issue by SpecificProtagonist** [Pscheidl/enum-collections#4]
Instead of performing a heap allocation, the backing array could be stored inline, avoiding a layer of indirection. Users for who
want the indirection can simply wrap the map/table in a `Box`. This provides a more composable API.

Unfortunately I'm not sure if this is possible before `const_generics_expr` gets stabilized.

**Comment by Pscheidl** [comment]
Agreed, would be great. Yeah, can't see how to make `EnumTable` & `EnumMap` with data field like `[V]`  `Sized` without const generics.
